### ISSUE TITLE
plugin is not working after Update to Zammad 5.3

### ISSUE THREAD

**Issue by catalincolesnicov** [Stubenhocker1399/zammad-addon-one-tab-only#1]
Hy,
after update to Zammad Version 5.3.1-1675764185.78abb1db.buster the addon isn't working anymore.

**Comment by catalincolesnicov** [comment]
Problem found....

after the upgrade to 5.3 following commands shoud be executed:

root> zammad run rake zammad:package:migrate
root> zammad run rake assets:precompile
root> systemctl restart zammad

**Comment by Stubenhocker1399** [comment]
Alright, cool you figured out the problem!

I've adjusted the readme slightly 7c375a200e6157a35d0abeed3e7750945af0b4ef so hopefully others won't have to stumble over this too! :smile:
